services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - /home/gary/pyriteview:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_MODE=${APP_MODE}
    image: php:7.1-fpm
    container_name: php-app
    volumes:
      - /home/gary/pyriteview:/var/www/html
      - /home/gary/pyriteview/vendor:/var/www/html/vendor
      - /home/gary/pyriteview/var:/var/www/html/var
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    environment:
      - APP_MODE=${APP_MODE:-development}  # Use the environment variable
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface
    networks:
      - app-network

networks:
  app-network:
    driver: bridge